/**
 * Created by Administrator on 2017/6/5.
 */
export default{
  home: {
    financeList: [{
      label: "金融产品",
      cssClass: "vv-flat-button",
      labelClass: "vv-label",
      icon: "account_balance",
      iconClass: "vv-icon"
    }, {
      label: "贷款产品",
      href: '/product/credit/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-sub-label",
      icon: "panorama_fish_eye",
      iconClass: "vv-sub-icon"
    }, {
      label: "信用卡",
      href: '/product/credit/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-sub-label",
      icon: "panorama_fish_eye",
      iconClass: "vv-sub-icon"
    }, {
      label: "理财产品",
      href: '/product/credit/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-sub-label",
      icon: "panorama_fish_eye",
      iconClass: "vv-sub-icon"
    }],
    gbList: [{
      label: "政银企对接",
      href: '/gb/info/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-label",
      icon: "forum",
      iconClass: "vv-icon"
    }, {
      label: "对接信息发布",
      href: '/gb/info/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-sub-label",
      icon: "panorama_fish_eye",
      iconClass: "vv-sub-icon"
    }, {
      label: "自由邀请洽谈",
      href: '/gb/meet/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-sub-label",
      icon: "panorama_fish_eye",
      iconClass: "vv-sub-icon"
    }, {
      label: "对接交流论坛",
      href: '/gb/discuss/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-sub-label",
      icon: "panorama_fish_eye",
      iconClass: "vv-sub-icon"
    }],
    serviceList: [{
      label: "特色服务",
      href: '/service/hot/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-label",
      icon: "room_service",
      iconClass: "vv-icon"
    }, {
      label: "个人征信查询",
      href: '/service/zx/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-sub-label",
      icon: "panorama_fish_eye",
      iconClass: "vv-sub-icon"
    }, {
      label: "附近银行",
      href: '/service/map/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-sub-label",
      icon: "panorama_fish_eye",
      iconClass: "vv-sub-icon"
    }, {
      label: "金融计算机",
      href: '/service/cacla/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-sub-label",
      icon: "panorama_fish_eye",
      iconClass: "vv-sub-icon"
    }, {
      label: "惠银帮办",
      href: '/service/help/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-sub-label",
      icon: "panorama_fish_eye",
      iconClass: "vv-sub-icon"
    }, {
      label: "信用卡优惠信息",
      href: '/service/credit/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-sub-label",
      icon: "panorama_fish_eye",
      iconClass: "vv-sub-icon"
    }],
    infoList: [{
      label: "金融资讯",
      href: '/service/credit/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-label",
      icon: "map",
      iconClass: "vv-icon"
    }, {
      label: "政策宣传",
      href: '/product/credit/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-sub-label",
      icon: "panorama_fish_eye",
      iconClass: "vv-sub-icon"
    }, {
      label: "金融论坛",
      href: '/product/credit/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-sub-label",
      icon: "panorama_fish_eye",
      iconClass: "vv-sub-icon"
    }, {
      label: "行业动态",
      href: '/product/credit/index',
      cssClass: "vv-flat-button",
      labelClass: "vv-sub-label",
      icon: "panorama_fish_eye",
      iconClass: "vv-sub-icon"
    }]
  }
};
